import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import ShowNavbar from "./components/navbar/showNavbar";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Prompt({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Anime Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ShowNavbar/>
          {children}
      </body>
    </html>
  );
}
