import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ShowNavbar from "./components/navbar/showNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anime Map",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ShowNavbar/>
          {children}
      </body>
    </html>
  );
}
